### ISSUE TITLE
Published time on feeds

### ISSUE THREAD

**Issue by crazy-max** [owncloudarchive/news#982]
Hi,

First of all thanks for this great app!
Yesterday i have migrated from Feedly to ownCloud News app.
Eveything seems fine except a "problem" with the items timestamp.

Feedly seems to be based on the `<published>` feed tag and ownCloud News is based on the `<updated>` feed tag to create the item timestamp.

![ownnote](https://cloud.githubusercontent.com/assets/1951866/14762157/02bb1a90-0974-11e6-8fed-a1e7f8bf994b.png)

![feedly](https://cloud.githubusercontent.com/assets/1951866/14762158/05bb33ec-0974-11e6-8667-a2f90ebcb3dc.png)

![rss](https://cloud.githubusercontent.com/assets/1951866/14762185/a4a50ab4-0974-11e6-8b21-fc5eeb7b098b.png)

For example on a Youtube RSS feeds channels the updated timestamp is over and over updated so the timestamp is not accurate for me (see screenshots and [this feed](https://www.youtube.com/feeds/videos.xml?channel_id=UCR4s1DE9J4DHzZYXMltSMAg))

Is there an option to only display published date and not updated date in the column ?

I saw a bugfix on 4.2.0 release, maybe it is related ? :

> Ignore Atom updated tag if it is earlier than the published tag

ownCloud : 9.0.1
ownCloud News: 8.7.1

Thanks!

**Comment by BernhardPosselt** [comment]
Hi @crazy-max !

This is a picofeed issue, can you open this issue there?

**Comment by BernhardPosselt** [comment]
https://github.com/fguillot/picoFeed

**Comment by crazy-max** [comment]
Hi @BernhardPosselt !

Ok i will add this issue there.

**Comment by crazy-max** [comment]
Indeed it's a picoFeed issue (example in `Parser/Atom.php` file) :

```php
$item->setDate(max($published, $updated)); // We use the most recent date between published and updated
```
I have [created an issue on their repository](https://github.com/fguillot/picoFeed/issues/267).
For the moment i have added a method to retrieve the published version on picoFeed parsers and change the code in the `feedfetcher.php` script of ownCloud News.

**Comment by BernhardPosselt** [comment]
Maybe you could create a pull request for picofeed  if you've already fixed it ;)

Keep in mind that not all feeds feature the published tag so a fallback should be considered

**Comment by crazy-max** [comment]
Yep i have a fallback too i will create a pull request ;)

**Comment by crazy-max** [comment]
I have made a comment on the picoFeed issue with the implementation of published / updated item date : https://github.com/fguillot/picoFeed/issues/267
I think i will fork ownCloud News too and add an implementation to let the choice to the user to choose between updated or published date.

**Comment by BernhardPosselt** [comment]
If we have a way to distinguish between updated and published, I think it would make sense to have both. Let's first get the picofeed PR merged, then start working on the News stuff ;D

Some tips:
* https://github.com/owncloud/news/blob/master/db/item.php#L57 would need an updatedDate similar to pubDate
* https://github.com/owncloud/news/blob/master/appinfo/database.xml#L296 is the database schema which would need an updated_date column similar to pub_date
* https://github.com/owncloud/news/blob/master/fetcher/feedfetcher.php#L243 would need a setter from the picofeed api

That and maybe some unit test adjustements should be all for the server side.

These are the places where the client side date is being rendered:
* https://github.com/owncloud/news/blob/master/templates/part.content.php#L59 for compact view
* https://github.com/owncloud/news/blob/master/templates/part.content.php#L106 in expanded view

We'd have to think of a way to integrate this in a way that is less intrusive:
* Don't show the updated date if its the same as the published date
* Either replace the published with the updated date or keep the published date were it is and display the updated date maybe somewhere below the heading, like: updated 1h ago

**Comment by crazy-max** [comment]
Totally agree but like you said let's focus on picoFeed first ;)
