### ISSUE TITLE
Add image item preview

### ISSUE THREAD

**Issue by crazy-max** [owncloudarchive/news#984]
By parsing the `<content>` to find the first `<img>` or retrieve the `<media:thumbnail>` (for RSS media) we can display a preview of a RSS item like Feedly :

![crazyws1](https://cloud.githubusercontent.com/assets/1951866/14832790/3e38533c-0bfc-11e6-8f0d-48a727f1057d.png)

![screenshot_2016-04-26-22-13-17](https://cloud.githubusercontent.com/assets/1951866/14832792/41ff8ab2-0bfc-11e6-91ac-eddb2f866e4c.png)

RSS 2 first image in content :

![firstimage](https://cloud.githubusercontent.com/assets/1951866/14833110/e1f87d16-0bfd-11e6-895c-a854c82ebd81.png)

RSS Media with media:thumbnail (youtube) :

![mediathumb](https://cloud.githubusercontent.com/assets/1951866/14833121/ee1fed9a-0bfd-11e6-9ca4-c828fc981792.png)

**Comment by BernhardPosselt** [comment]
Good idea, should be added to picoFeed first and retrieved via $item->getThumbnail(). This should only be done for the \<media:thumbnail> however since this will cause issues when the first image is not a thumbnail (think of comics)

**Comment by crazy-max** [comment]
I think we need to retrieve the image link from picoFeed like you said but for <media:thumbnail> and the first picture in content. Then the method would be `$item->getImage()`
In ownCloud News we can process picture exceeding a predefined size (64x64) using GD2 library and crop to square then resize for example ?

**Comment by crazy-max** [comment]
If there are no picture in the rss item, we can put a default picture like the ownCloud News logo ?

**Comment by BernhardPosselt** [comment]
I'd go for the following:
* First picture in the content may be any image and may also produce false positives, espially for comic feeds. Showing a thumbnail which is basically a very tiny comic image makes no sense, we should avoid that
* No resizing, simply set a css max-height property and the browser will resize it. We can always make it bigger or smaller later on
* If a thumbnail is discovered and it has the same URL as the first image, we strip the image from the content. That way we we don't add the same image twice
* The thumbnail will be added with nice padding at the top left

I see the main purpose for the thumbnail in adding a proper padding to the first image.

**Comment by crazy-max** [comment]
Seems nice :)

**Comment by crazy-max** [comment]
Is this owncloud plugin not maintained anymore? Or merged to nextcloud?
